# Generated by Django 5.1.1 on 2024-10-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_books_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
